name: 'Checkout and Prep cFS Bundle'
description: 'Checkouts the bundle and sets up everything'
inputs:
  bundle-branch:  
    description: 'Branch to check out from nasa/cfs repository'
    default: 'main'
runs:
  using: "composite"
  steps:
        # Checks out a copy of your repository on the ubuntu-latest machine
        - name: Checkout bundle code
          run: |
            pwd
            ls           
            git checkout https://github.com/nasa/cfs          
            cd cfs
          shell: bash
        
        # Setup the build system
        - name: Copy Files
          run: |
            cd cfs
            cp ./cfe/cmake/Makefile.sample Makefile
            cp -r ./cfe/cmake/sample_defs sample_defs
          shell: bash

        # Setup the build system
        - name: Make Prep
          run: |
            cd cfs
            make prep
          env:
            SIMULATION: native
          shell: bash
          
