name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

env:
  SIMULATION: native
    
jobs:   
    
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-exec:
    # Name the Job
    name: Build Executables
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Install cmake
#       - name: get-cmake
#         uses: lukka/get-cmake        
            
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get submodules
        uses: textbook/git-checkout-submodule-action@2.1.1

      # Setup the build system
      - name: Copy Files
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs
          
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

        
      # Setup the build system
      - name: Make Prep
        if: steps.cache-build.outputs.cache-hit !='true'
        run: make prep
        
      - name: Make Install
        run: make install
