name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-exec:
    # Name the Job
    name: Build Executables
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Install cmake
#       - name: get-cmake
#         uses: lukka/get-cmake        
            
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup the build system
      - name: Copy Files
        run: |
          cd cfe
          ls
#          cp ./cfe/Makefile.sample Makefile
 #         cp ./cfe/sample_defs sample_defs             
        
      # Setup the build system
      - name: Make Prep
        env:
          SIMULATION: native
        run: make prep
        

