name: Static Analysis

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:

  static-analysis:
    name: Run cppcheck
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        cppcheck: [bundle, cfe, osal, psp]

    steps:

      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y

        # Checks out a copy of the cfs bundle
      - name: Checkout code
        uses: astrogeco/cfs@create-custom-action

      - name: Run bundle cppcheck
        if: ${{matrix.cppcheck =='bundle'}}
        run: cppcheck --force --inline-suppr --quiet . 2> ${{matrix.cppcheck}}_cppcheck_err.txt

        # Run strict static analysis for embedded portions of cfe, osal, and psp
      - name: cfe strict cppcheck
        if: ${{matrix.cppcheck =='cfe'}}
        run: |
          cd ${{matrix.cppcheck}}
          cppcheck --force --inline-suppr --std=c99 --language=c --enable=warning,performance,portability,style --suppress=variableScope --inconclusive ./fsw/cfe-core/src ./modules 2> ../${{matrix.cppcheck}}_cppcheck_err.txt

      - name: osal strict cppcheck
        if: ${{matrix.cppcheck =='osal'}}
        run: |
          cd ${{matrix.cppcheck}}
          cppcheck --force --inline-suppr --std=c99 --language=c --enable=warning,performance,portability,style --suppress=variableScope --inconclusive ./src/bsp ./src/os 2> ../${{matrix.cppcheck}}_cppcheck_err.txt

      - name: psp strict cppcheck
        if: ${{matrix.cppcheck =='psp'}}
        run: |
          cd ${{matrix.cppcheck}}
          cppcheck --force --inline-suppr --std=c99 --language=c --enable=warning,performance,portability,style --suppress=variableScope --inconclusive ./fsw 2> ../${{matrix.cppcheck}}_cppcheck_err.txt

      - name: Archive Static Analysis Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.cppcheck}}-cppcheck-err
          path: ./*cppcheck_err.txt

      - name: Check for errors
        run: |
          if [[ -s ${{matrix.cppcheck}}_cppcheck_err.txt ]];
          then
            cat ${{matrix.cppcheck}}_cppcheck_err.txt
            exit -1
          fi
