name: Test Action

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:

  static-analysis:
    name: Run cppcheck
    runs-on: ubuntu-18.04
    steps:

      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y

        # Checks out a copy of the cfs bundle
      - name: Checkout code
        uses: astrogeco/cfs@create-custom-action

      - name: Run bundle cppcheck
        run: cppcheck --force --inline-suppr --quiet . 2> cppcheck_err.txt

      - name: Check for errors
        run: |
          if [[ -s cppcheck_err.txt ]];
          then
            cat cppcheck_err.txt
            exit -1
          fi
